<%-- Peter Marchese --%>

<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<% 
ArrayList rs = (ArrayList)request.getAttribute("rs");
%>

<html>
   <head>
      <title>Revenue Generated</title>
   </head>
   <body>
   <form action="./revgen" method="post">
   <input type = "text" name="flight" placeholder="flight">
   <br/>
   <br/>
   <input type = "text" name="airline" placeholder="airline">
   <br/><br/>
   <input type = "text" name = customer placeholder="customer">
   <br/><br/>
   <input type = "submit" name = "submit">
   </form>
      
   <table style="width: 65%; ">
    <tr>
    <tr>
    <th>Revenue Generated by Input</th>
    </tr>
    
    <%
    if (rs != null){
       float total = 0;
       float value = 0;
       for(int i = 0; i < rs.size(); i++) { 
        Dictionary row = (Hashtable)rs.get(i);
        %>
            <tr style='font-size: large;'>
            <%
            int numfirst = Integer.valueOf((String) row.get("num_first_class"));
            int farefirst = Integer.valueOf((String) row.get("fare_first"));
            int numecon = Integer.valueOf((String) row.get("num_economy"));
            int fareecon = Integer.valueOf((String) row.get("fare_econ"));
            value = numfirst*farefirst + numecon*fareecon;
            total = total + value;
            %>
            <td>
            <%= value %>
            </td>
            </tr>
    
    <% } %>
    <td><%= total %></td>
<% } %>
    
    </table>
   </body>
   </html>